scheapp/config/routes.rb
Rails.application.routes.draw do
  get 'plans/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

resources:plans
end

scheapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

scheapp/app/models/plan.rb
class Plan < ApplicationRecord
    validates :title, presence: true
    validates :startday, presence: true
    validates :finday, presence: true
    validate :start_end_check
     def start_end_check
       errors.add(:finday, "は開始日より前の日付は登録できません。") unless
       self.startday <= self.finday 
     end
  
end

scheapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

scheapp/app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(params.require(:plan).permit(:title, :startday, :finday, :allday, :detail))
    if @plan.save
      flash[:notice]="スケジュールを新規登録しました"
      redirect_to :plans
    else 
      render "new"
    end
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update(params.require(:plan).permit(:title, :startday, :finday, :allday, :detail))
      flash[:notice]="スケジュールを更新しました"
      redirect_to :plans
    else 
      render "edit"
    end
  end

  def destroy
    @plan = Plan.find(params[:id])
     @plan.destroy
      flash[:notice] = "スケジュールを削除しました"
      redirect_to :plans
  end
end

scheapp/app/helpers/application_helper.rb
module ApplicationHelper
end

scheapp/app/helpers/plans_helper.rb
module PlansHelper
end

scheapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header>
    <p class= "main_title">Ruby on Ralis スケジュール管理アプリ</p>
   </header>

   <%= yield %>

   <footer>
   <p class= "main_title">今日の日付 <%= Date.today %></p> 
   </footer>
  </body>
</html>

scheapp/app/views/plans/edit.html.erb
<h1>スケジュール編集</h1>
 
<%= form_with model: @plan do |f| %>
<table>
 <tr>
  <th class="label"><%= f.label :title, 'タイトル' %></th>
  <td class="field"><%= f.text_field :title %></td>
 </tr>

 <tr>
  <th class="label"><%= f.label :startday, '開始日' %></th>
  <td class="field"><%= f.date_field :startday, value: Time.now.strftime("%Y-%m-%d") %></td>
 </tr>

 <tr>
  <th class="label"><%= f.label :finday, '終了日' %></th>
  <td class="field"><%= f.date_field :finday, value: Time.now.strftime("%Y-%m-%d")%></td>
 </tr>

 <tr>
  <th class="label"><%= f.label :allday, '終日' %></th>
  <td class="field"><%= f.check_box :allday,{}, '◯', '×' %>
  <p>終日の場合はチェックを入れます</p></td>
 </tr>

 <tr>
  <th class="label_de"><%= f.label :detail, '詳細' %></th>
  <td class="field_de"><%= f.text_area :detail, size:"40x5" %></td>
 </tr>
</table>

<div>
 <ul>
  <li><%=f.submit "編集を完了する" %></li>
  <li><%= link_to "一覧へ戻る", :plans %></li>
 </ul>
</div>
<% end %>

scheapp/app/views/plans/index.html.erb
<h3>ユーザー情報一覧</h3>

<% if flash[:notice] %>
 <p class= "notice"><%= flash[:notice] %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th class="tag_button">id</th>
      <th class="tag">タイトル</th>
      <th class="tag">開始日</th>
      <th class="tag">終了日</th>
      <th class="tag_button">終日</th>
      <th class="tag_de">詳細</th>
      <th class="tag">更新日</th>
      <th class="tag_button">確認</th>
      <th class="tag_button">編集</th>
      <th class="tag_button">削除</th>
    </tr>
  </thead>
  <tbody>
  <% @plans.each do |plan| %>
   <tr>
    <td class="content_button"><%= plan.id %></td>
    <td class="content"><%= plan.title %></td>
    <td class="content"><%= plan.startday %></td>
    <td class="content"><%= plan.finday %></td>
    <td class="content_button"><%= plan.allday %></td>
    <td class="content_de"><%= plan.detail %></td>
    <td class="content"><%= plan.updated_at.to_s(:datetime_jp) %></td>
    <td class="content_button"><%= link_to"参照", plan_path(plan) %></td>
    <td class="content_button"><%= link_to"編集", edit_plan_path(plan) %></td>
    <td class="content_button"><%= link_to "削除", plan_path(plan), method: :delete, data: { confirm: "本当に削除しますか？" } %>
    </td>
    </tr>
  <% end %>
 </tbody>
</table>

<p><%= link_to "スケジュール新規登録", :new_plan %></p>

scheapp/app/views/plans/new.html.erb
<h1>スケジュール新規作成</h1>

<%= render "shared/error_message", obj:@plan %>
 
<%= form_with model: @plan do |f| %>
<table>
 <tr>
  <th class="label"><%= f.label :title, 'タイトル' %></th>
  <td class="field"><%= f.text_field :title %></td>
 </tr>

 <tr>
  <th class="label"><%= f.label :startday, '開始日' %></th>
  <td class="field"><%= f.date_field :startday, value: Time.now.strftime("%Y-%m-%d")%></td>
 </tr>

 <tr>
  <th class="label"><%= f.label :finday, '終了日' %></th>
  <td class="field"><%= f.date_field :finday, value: Time.now.strftime("%Y-%m-%d")%></td>
 </tr>

 <tr>
  <th class="label"><%= f.label :allday, '終日' %></th>
  <td class="field"><%= f.check_box :allday,{}, '◯', '×' %>
  <p>終日の場合はチェックを入れます</p></td>
 </tr>

 <tr>
  <th class="label_de"><%= f.label :detail, '詳細' %></th>
  <td class="field_de"><%= f.text_area :detail, size:"40x5" %></td>
 </tr>
</table>

<div>
 <ul>
  <li><%=f.submit "入力完了する" %></li>
  <li><%= link_to "一覧へ戻る", :plans %></li>
 </ul>
</div>
<% end %>

scheapp/app/views/plans/show.html.erb
<h3>スケジュール詳細</h3>

<table>
 <tr>
  <th class="label">タイトル</th>
  <td class="field"><%= @plan.title %></td>
 </tr>

 <tr>
  <th class="label">開始日</th>
  <td class="field"><%= @plan.startday %></td>
 </tr>

 <tr>

 <th class="label">終了日</th>
 <td class="field"><%= @plan.finday %></td>
</tr>

<tr>
  <th class="label">終日</th>
  <td class="field"><%= @plan.allday %></td>
 </tr>

 <tr>
  <th class="label">詳細</th>
  <td class="field"><%= @plan.detail %></td>
 </tr>
</table>

<div>
 <ul>
  <li><%= link_to "編集する" , edit_plan_path(@plan) %></li>
  <li><%= link_to "一覧へ戻る", :plans %></li>
 </ul>
</div>

scheapp/app/views/shared/_error_message.html.erb
<% if obj.errors.any? %>
 <% obj.errors.full_messages.each do |message| %>
  <ul>
   <li><%= message %></li>
  </ul>
 <% end %>
<% end %>